# Resmi Python Imajini kullanma
FROM python:3.12-slim

# Calisma Dizinini Ayarlama
WORKDIR /app

# Gereksinim dosyasini kopyalama ve kutuphaneleri kurma
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Proje dosyalarini konteynira aktarma
COPY . .

# Streamlit Portunu Dısari Cıkarma
EXPOSE 8501

# Konteynir ayaga kalktiginda uygulamayi baslatma
CMD ["Streamlit", "run", "app.py", "--server.address=0.0.0.0"]