# Resmi Python imajini kullanma
FROM python:3.12-slim

# Calisma dizinini belirleme
WORKDIR /app

# Gerekli dosyalari konteynira kopyalama
COPY requirements.txt .

# Bagimliliklari yukleme
RUN pip install --no-cache-dir -r requirements.txt

# Proje dosyalarinin tamamini kopyalama
COPY . .

# Flask uygulamasinin calisacagi portu belirtme
EXPOSE 5000

# Uygulamayı başlatma
CMD ["python", "app.py"]