# Resmi Python imajını kullan
FROM python:3.12-slim

# Çalışma dizinini belirle
WORKDIR /app

# Gereksinim dosyasını kopyala ve kütüphaneleri yükle
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Tüm kodlarımızı konteynerin içine kopyala
COPY . .

# Flask'in çalıştığı 5000 portunu dışarıya aç
EXPOSE 5000

# Uygulamayı başlat
CMD ["python", "app.py"]